#!/bin/bash
#NOTE: Link configuration file to specified env before uploading
./link_config $1
if [ -z $1 ] || [ $1 == "dev" ]
then
  echo "Uploading to dev.novagrade.com"
  rsync -avz --exclude-from=.rsync-exclude ./ novagrade:~/dev.novagrade.com
  ssh novagrade 'chmod +xr -R dev.novagrade.com'
fi
if [ $1 == "prod" ]
then
  read -p "Are you sure? You want to upload to www.novagrade.com (Y/[N])" -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "Uploading to www.novagrade.com"
    rsync -avz --exclude-from=.rsync-exclude ./ novagrade:~/public_html
  fi
fi
#NOTE: Always revert back to local configuration
./link_config
