#!/bin/bash
vagrant ssh --command "mysqldump novagrade_development > /vagrant/novagrade_dev.sql"
rsync -avz novagrade_dev.sql novagrade_hostname.sql novagrade:~/
if [ $1 == "restore" ]
then
  ssh novagrade 'bash -s' < restore
fi
